version: '3.1'

secrets:
  SECRET_TOKEN:
    external: true
# todo make postgres user/pw a SECRET
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=c17n
      - POSTGRES_PASSWORD=c17n
  app:
    build: .
    environment:
      - DOCKER_BUILDKIT=1
      - SPRING_PROFILES_ACTIVE
    secrets:
      - SECRET_TOKEN
    ports:
      - "9000:8080"
    depends_on:
      - db
