version: '3.1'

secrets:
  SECRET_TOKEN:
    external: true

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=c17n
      - POSTGRES_PASSWORD=c17n
  app:
    image: openjdk:16-alpine
#    build:
#      context: .
    ports:
      - "9000:8080"
    environment:
      - SECRET_TOKEN
    depends_on:
      - db
